default: help
.PHONY: default


help:
	@echo 'Usage:'
	@echo '	make'
	@echo '	make help'
	@echo '	make add'
	@echo '	make commit'
	@echo '	make push'
.PHONY: help


add:
	@./add.sh
.PHONY: add


commit:
	@./commit.sh
.PHONY: commit


push:
	@./push.sh
.PHONY: push
