default: help
.PHONY: default


help:
	@echo 'Usage:'
	@echo '	make'
	@echo '	make help'
	@echo '	make create'
	@echo '	make serve'
	@echo '	make browse'
.PHONY: help


create:
	@./create.sh
.PHONY: create


serve:
	@./serve.sh
.PHONY: serve


browse:
	@./browse.sh
.PHONY: browse
