default: help
.PHONY: default


help:
	@echo 'Usage:'
	@echo '	make'
	@echo '	make help'
	@echo '	make create'
	@echo '	make view'	
	@echo '	make remove'
.PHONY: help


create:
	@./create.sh
.PHONY: create


remove:
	@./remove.sh
.PHONY: remove


view:
	@./view.sh
.PHONY: view
